
package com.example.interview.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-13T14:50:06.448+03:00
 * Generated source version: 3.4.4
 *
 */
public final class CalculatorSoap_CalculatorSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Calculator");

    private CalculatorSoap_CalculatorSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Calculator.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        int intA = 100;
        int intB = 150;

        Calculator ss = new Calculator(wsdlURL, SERVICE_NAME);
        CalculatorSoap port = ss.getCalculatorSoap12();
        {
            System.out.println("Invoking subtract...");
            int _subtract__return = port.subtract(intA, intB);
            System.out.println("subtract.result=" + _subtract__return);
        }
        {
            System.out.println("Invoking divide...");
            int _divide__return = port.divide(intA, intB);
            System.out.println("divide.result=" + _divide__return);
        }
        {
            System.out.println("Invoking add...");
            int _add__return = port.add(intA, intB);
            System.out.println("add.result=" + _add__return);
        }
        {
            System.out.println("Invoking multiply...");
            int _multiply__return = port.multiply(intA, intB);
            System.out.println("multiply.result=" + _multiply__return);
        }
        System.exit(0);
    }

}
